### ISSUE TITLE
powershell.exe has default registry override for colours

### ISSUE THREAD

**Issue by TBBle** [neilpa/cmd-colors-solarized#18]
Repeating https://github.com/neilpa/cmd-colors-solarized/issues/14#issuecomment-282711792:

> There's a registry key in `HKEY_CURRENT_USER\Console` for `%SystemRoot%_System32_WindowsPowerShell_v1.0_powershell.exe` which contains entries overriding the registry setting you've imported.
>
> You can either delete/rename those keys (`PopupColors`, `ScreenColors` and anything starting with `ColorTable`), or update them to match the registry file you chose ([solarized-dark.reg](https://github.com/neilpa/cmd-colors-solarized/blob/master/solarized-dark.reg) or [solarized-light.reg](https://github.com/neilpa/cmd-colors-solarized/blob/master/solarized-light.reg)).
>
> There's also (on a 64-bit system) a `%SystemRoot%_SysWOW64_WindowsPowerShell_v1.0_powershell.exe` key for the 32-bit powershell executable.

This shows up when the background and text colour of a powershell instance started by "Start->Run->powershell", i.e. not via a shortcut, is not affected by the registry file.

We probably need some way of addressing this, either in the documentation or with some kind of install script?

**Comment by TonyApuzzo** [comment]
I have to confess that I am totally confused by how the install is supposed to work for PowerShell, CMD, Windows bash, etc. on Windows 10.  I installed the registry file and added the line to my `$profile` but nothing changed from what I can tell.  Then I deleted the ```HKEY_CURRENT_USER\Console\%SystemRoot%_System32_WindowsPowerShell_v1.0_powershell.exe``` and ```HKEY_CURRENT_USER\Console\XXX%SystemRoot%_SysWOW64_WindowsPowerShell_v1.0_powershell.exe``` and it still made no difference.  Then after reading more about the start menu's powershell being different, I manually added my own shortcut for powershell using New->Shortcut->powershell.exe, when I launch from that icon I get a black background and the foreground color for arguments is dark blue which is terrible! 

How is this *supposed* to work?  The install instructions are either wrong or too terse.  I ASSuMEd that once I installed the registry file I would start getting the updated colors, but maybe I have to run a ps1 file or something?

**Comment by TBBle** [comment]
@TonyApuzzo To be clear, did you copy the two `Set-Solarised*ColorDefaults.ps1` files into `%UserProfile%\Documents\WindowsPowerShell`? The line added to your profile.ps1 executes one of those two files every time you start powershell.

**Comment by TonyApuzzo** [comment]
Something isn't right with my general settings I guess.  I did put the profile line in, but the profile doesn't actually do anything because `$HOST.UI.RawUI.BackgroundColor.ToString()` returns DarkMagenta on my system instead of Black or White.  Not that I have anything that is DarkMagenta that I can find :-)

When I manually run `Set-SolarizedDarkColorDefaults.ps1` it does set some colors, but the contrast is totally messed up for both Dark and Light.

I'm using the default branch in git, maybe there is a better branch?

```
PS U:\> $profile
C:\Users\tapuzzo\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1

PS U:\> more $profile . (Join-Path -Path (Split-Path -Parent -Path $PROFILE) -ChildPath $(switch($HOST.UI.RawUI.BackgroundColor.ToString()){'White'{'Set-SolarizedLightColorDefaults.ps1'}'Black'{'Set-SolarizedDarkColorDefaults.ps1'}default{return}}))

PS U:\> $HOST.UI.RawUI.BackgroundColor.ToString()
DarkMagenta
PS U:\>
```

**Comment by TonyApuzzo** [comment]
UPDATE: Loading the registry as 'admin' (or double-clicking on the file rather than running from the powershell command line) fixes my problem.  Apparently my situation was cause by the registry file not being loaded correctly.

If I use the Windows search or right-click on the start window, I still get the blue/white stock theme, but if I run powershell from a new shortcut on the desktop then I get the solarized colors.  So I think now I'm in the same situation as everyone else.

**Comment by TBBle** [comment]
Yeah, the 'Windows Search' result "Windows PowerShell" is a shortcut, you can either fix it by hand (painful!) or wait for #19 to get done.

**Comment by TBBle** [comment]
Explanation of the registry keys can be found via https://github.com/neilpa/cmd-colors-solarized/issues/19#issuecomment-311493124.

The short answer is that they're loaded from and written to *only* if you don't run the program via a shortcut.

Since the documentation recommends only updating the Shortcuts, there's no strong motivation to add these keys to the documentation.

So closing this issue.

**Comment by MJMultari** [comment]
Created a new shortcut and everything works perfectly!
