### ISSUE TITLE
Invisible letters

### ISSUE THREAD

**Issue by AlesMenzel** [neilpa/cmd-colors-solarized#29]
The DarkGrey color is so dark its hardly visible which makes life missarbale with a simple `git commit -m "..."` command as you cant even see the `-m`

![](https://image.prntscr.com/image/_N2rDEDATwKyGEKoLn8iyw.png)

**Comment by rbeesley** [comment]
I don't think you are having your defaults set correctly. I believe the issue is that [Set-SolarizedDarkColorDefaults.ps1](../blob/master/Set-SolarizedDarkColorDefaults.ps1) is not being executed. If it were rendering correctly, the quotes would be light blue as well. Since this is an elevated process, did you start it from Win-X?

**Comment by AlesMenzel** [comment]
Thank you, i was actually missing the last step of installation. There is said to add some code into a profile but there was never shown how to create one.

To create it, run (powershell):

`New-Item -path $profile -type file –force`

You might not need to use --force, but it didn´t work for me without it.
